/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ProductController;
import java.awt.Color;
import java.awt.Cursor;
import model.ProductModel;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.border.Border;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sthaa
 */
public class manageproducts extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(manageproducts.class.getName());
    private ProductController productController;

    /**
     * Creates new form manageproducts
     */
    Color defaultBg;
    Color defaultFg;
    Cursor defaultCursor;
    Border defaultBorder;
    Color normalBg;
    Color normalFg;
    Cursor normalCursor;
    Border normalBorder;
    Color originalBg;
    Color originalFg;
    Cursor originalCursor;
    Border originalBorder;
    public manageproducts() {
        initComponents();
        productController = new ProductController();
        loadProductsToTable();
       
        background.addMouseListener(new MouseAdapter() {
            @Override
        public void mousePressed(MouseEvent e) {
            closeNotificationIfOpen();
            }
        });
        defaultBg = delete.getBackground();
        defaultFg = delete.getForeground();
        defaultCursor = delete.getCursor();
        defaultBorder = delete.getBorder();
        normalBg = edit.getBackground();
        normalFg = edit.getForeground();
        normalCursor = edit.getCursor();
        normalBorder = edit.getBorder();
        originalBg = addproduct.getBackground();
        originalFg = addproduct.getForeground();
        originalCursor = addproduct.getCursor();
        originalBorder = addproduct.getBorder();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        mainlogo = new javax.swing.JPanel();
        rentifylogo = new javax.swing.JLabel();
        profile = new javax.swing.JPanel();
        ProfileIcon = new javax.swing.JLabel();
        notification = new javax.swing.JPanel();
        notificationicon = new javax.swing.JButton();
        center = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        dashboard = new javax.swing.JButton();
        Users = new javax.swing.JButton();
        Statistics = new javax.swing.JButton();
        ManageProducts = new javax.swing.JButton();
        Invoice = new javax.swing.JButton();
        Calender = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductTable = new javax.swing.JTable();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        addproduct = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(249, 250, 251));
        background.setPreferredSize(new java.awt.Dimension(1280, 720));

        mainlogo.setBackground(new java.awt.Color(249, 250, 251));

        rentifylogo.setBackground(new java.awt.Color(249, 250, 251));
        rentifylogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/rentifyohnebg (1).png"))); // NOI18N

        javax.swing.GroupLayout mainlogoLayout = new javax.swing.GroupLayout(mainlogo);
        mainlogo.setLayout(mainlogoLayout);
        mainlogoLayout.setHorizontalGroup(
            mainlogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainlogoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(rentifylogo))
        );
        mainlogoLayout.setVerticalGroup(
            mainlogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainlogoLayout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addComponent(rentifylogo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        profile.setBackground(new java.awt.Color(249, 250, 251));
        profile.setPreferredSize(new java.awt.Dimension(60, 60));

        ProfileIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProfileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/profile icon.png"))); // NOI18N
        ProfileIcon.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout profileLayout = new javax.swing.GroupLayout(profile);
        profile.setLayout(profileLayout);
        profileLayout.setHorizontalGroup(
            profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileLayout.createSequentialGroup()
                .addComponent(ProfileIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        profileLayout.setVerticalGroup(
            profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileLayout.createSequentialGroup()
                .addComponent(ProfileIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        notification.setBackground(new java.awt.Color(249, 250, 251));
        notification.setPreferredSize(new java.awt.Dimension(32, 32));

        notificationicon.setBackground(new java.awt.Color(249, 250, 251));
        notificationicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/notification.png"))); // NOI18N
        notificationicon.setBorder(null);
        notificationicon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        notificationicon.setFocusPainted(false);
        notificationicon.setPreferredSize(new java.awt.Dimension(32, 32));
        notificationicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notificationiconMouseClicked(evt);
            }
        });
        notificationicon.addActionListener(this::notificationiconActionPerformed);

        javax.swing.GroupLayout notificationLayout = new javax.swing.GroupLayout(notification);
        notification.setLayout(notificationLayout);
        notificationLayout.setHorizontalGroup(
            notificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, notificationLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(notificationicon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        notificationLayout.setVerticalGroup(
            notificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notificationLayout.createSequentialGroup()
                .addComponent(notificationicon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        center.setBackground(new java.awt.Color(255, 255, 255));
        center.setPreferredSize(new java.awt.Dimension(1237, 600));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(209, 213, 219));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        dashboard.setBackground(new java.awt.Color(229, 231, 235));
        dashboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dashboard.setForeground(new java.awt.Color(107, 114, 128));
        dashboard.setText("Dashboard");
        dashboard.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(193, 193, 193), 2, true));
        dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardMouseExited(evt);
            }
        });
        dashboard.addActionListener(this::dashboardActionPerformed);

        Users.setBackground(new java.awt.Color(229, 231, 235));
        Users.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Users.setForeground(new java.awt.Color(107, 114, 128));
        Users.setText("Users");
        Users.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(193, 193, 193), 2, true));
        Users.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UsersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UsersMouseExited(evt);
            }
        });
        Users.addActionListener(this::UsersActionPerformed);

        Statistics.setBackground(new java.awt.Color(229, 231, 235));
        Statistics.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Statistics.setForeground(new java.awt.Color(107, 114, 128));
        Statistics.setText("Statistics");
        Statistics.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(193, 193, 193), 2, true));
        Statistics.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Statistics.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StatisticsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StatisticsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StatisticsMouseExited(evt);
            }
        });
        Statistics.addActionListener(this::StatisticsActionPerformed);

        ManageProducts.setBackground(new java.awt.Color(229, 231, 235));
        ManageProducts.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ManageProducts.setForeground(new java.awt.Color(107, 114, 128));
        ManageProducts.setText("Manage Products");
        ManageProducts.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(38, 166, 154), 2, true));
        ManageProducts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ManageProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageProductsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ManageProductsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ManageProductsMouseExited(evt);
            }
        });
        ManageProducts.addActionListener(this::ManageProductsActionPerformed);

        Invoice.setBackground(new java.awt.Color(229, 231, 235));
        Invoice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Invoice.setForeground(new java.awt.Color(107, 114, 128));
        Invoice.setText("Invoice");
        Invoice.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(193, 193, 193), 2, true));
        Invoice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Invoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InvoiceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InvoiceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InvoiceMouseExited(evt);
            }
        });
        Invoice.addActionListener(this::InvoiceActionPerformed);

        Calender.setBackground(new java.awt.Color(229, 231, 235));
        Calender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Calender.setForeground(new java.awt.Color(107, 114, 128));
        Calender.setText("Calender");
        Calender.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(193, 193, 193), 2, true));
        Calender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Calender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalenderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CalenderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CalenderMouseExited(evt);
            }
        });
        Calender.addActionListener(this::CalenderActionPerformed);

        logout.setBackground(new java.awt.Color(38, 166, 154));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Log out");
        logout.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(193, 193, 193), 2, true));
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        logout.addActionListener(this::logoutActionPerformed);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        ProductTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Image", "Price", "Synopsis", "Type", "Form", "QTY"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ProductTable.setRowHeight(30);
        jScrollPane1.setViewportView(ProductTable);

        edit.setForeground(new java.awt.Color(2, 62, 138));
        edit.setText("EDIT");
        edit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(193, 193, 193), 2, true));
        edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editMouseExited(evt);
            }
        });

        delete.setForeground(new java.awt.Color(220, 38, 38));
        delete.setText("DELETE");
        delete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(193, 193, 193), 2, true));
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteMouseExited(evt);
            }
        });

        addproduct.setBackground(new java.awt.Color(0, 102, 204));
        addproduct.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        addproduct.setForeground(new java.awt.Color(255, 255, 255));
        addproduct.setText("ADD PRODCT");
        addproduct.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(193, 193, 193), 2, true));
        addproduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addproduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addproductMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addproductMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addproductMouseExited(evt);
            }
        });

        javax.swing.GroupLayout centerLayout = new javax.swing.GroupLayout(center);
        center.setLayout(centerLayout);
        centerLayout.setHorizontalGroup(
            centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Users, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Statistics, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManageProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Invoice, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Calender, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(centerLayout.createSequentialGroup()
                        .addGap(388, 388, 388)
                        .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(centerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 989, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centerLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(addproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        centerLayout.setVerticalGroup(
            centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(centerLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Users, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Statistics, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ManageProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Invoice, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Calender, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centerLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(addproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18)
                .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(mainlogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(877, 877, 877)
                        .addComponent(notification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(center, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(notification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addComponent(mainlogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(center, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     private void loadProductsToTable() {
        DefaultTableModel model = (DefaultTableModel) ProductTable.getModel();
        model.setRowCount(0); 

        for (ProductModel p : productController.getAllProducts()) {
            model.addRow(new Object[]{
                p.getProductID(),
                p.getProductName(),
                p.getProductImage(),
                p.getProductPrice(),
                p.getProductSynopsis(),
                p.getProductType(),
                p.getProductForm(),
                p.getProductQuantity()
            });
        }
    }
     private static final int LOW_QTY_THRESHOLD = 10;

    private java.util.List<ProductModel> getLowStockPhysicalBooks() {
    java.util.List<ProductModel> low = new java.util.ArrayList<>();
    for (ProductModel p : productController.getAllProducts()) {
        if ("Book".equalsIgnoreCase(p.getProductType())
                && "Physical".equalsIgnoreCase(p.getProductForm())
                && p.getProductQuantity() <= LOW_QTY_THRESHOLD) {
            low.add(p);
        }
    }
    return low;
}

    String buildLowStockMessage() {
    java.util.List<ProductModel> low = getLowStockPhysicalBooks();
    if (low.isEmpty()) {
        return "No low-stock physical books.";
    }

    URL imgUrl = getClass().getResource("/icons/low-stock.png");

    StringBuilder sb = new StringBuilder();
    sb.append("<html>")
      .append("<div style='display:flex;align-items:center;'>")
      .append("<img src='").append(imgUrl).append("' ")
      .append("style='width:40px;height:40px;margin-right:10px;'/>")
      .append("<div>")
      .append("<div><b>Low stock books:</b></div>");

    for (ProductModel p : low) {
        sb.append(p.getProductName())
          .append(" (QTY: ")
          .append(p.getProductQuantity())
          .append(")<br>");
    }
    sb.append("</html>");
    return sb.toString();
}
    
    private notification adWindow;
    private javax.swing.Timer rollTimer;

    private final int X = 870;
    private final int Y = 110;
    private final int FULL_HEIGHT = 400;;
    private boolean isOpen = false;
    private void notificationiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notificationiconMouseClicked

        if (adWindow == null) {
            adWindow = new notification();
            adWindow.setSize(300, 0);
        }
        
        String msg = buildLowStockMessage();
        adWindow.setMessage(msg);
        

        if (rollTimer != null && rollTimer.isRunning()) {
            rollTimer.stop();
        }
        
        int xOffset = -14;   
        int yOffset = 5;  
        Point p = notificationicon.getLocationOnScreen();   
        int x = p.x + notificationicon.getWidth() - adWindow.getWidth() + xOffset; 
        int y = p.y + notificationicon.getHeight() + yOffset;
        adWindow.setLocation(x, y);

        if (!isOpen) {
            rollDown();
        } else {
            rollUp();
        }
    }

    private void rollDown() {
        adWindow.setVisible(true);
        adWindow.toFront();

        rollTimer = new Timer(10, e -> {
            int h = adWindow.getHeight();

            if (h < FULL_HEIGHT) {
                adWindow.setSize(300, h + 20);
            } else {
                adWindow.setSize(300, FULL_HEIGHT);
                isOpen = true;
                rollTimer.stop();
            }
        });

        rollTimer.start();
    }

    private void rollUp() {
        rollTimer = new Timer(10, e -> {
            int h = adWindow.getHeight();

            if (h > 0) {
                adWindow.setSize(300, h - 10);
            } else {
                adWindow.setSize(300, 0);
                adWindow.setVisible(false);
                isOpen = false;
                rollTimer.stop();
            }
        });

        rollTimer.start();
    }//GEN-LAST:event_notificationiconMouseClicked
    
    private void closeNotificationIfOpen() {
    if (adWindow != null && adWindow.isVisible()) {
        if (rollTimer != null && rollTimer.isRunning()) {
            rollTimer.stop();
        }
        adWindow.setVisible(false);
        adWindow.dispose();   
        adWindow = null;
        isOpen = false;
        }
    }
    
    private void notificationiconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationiconActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_notificationiconActionPerformed

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        // TODO add your handling code here:
        Point loc = this.getLocation();
        if (adWindow != null && adWindow.isVisible()) {
        adWindow.setVisible(false);
        adWindow.dispose();
        adWindow = null;
        }
        this.dispose();

        admindashboard ad = new admindashboard();
        ad.setLocation(loc);
        ad.setVisible(true);
    }//GEN-LAST:event_dashboardMouseClicked

    private void dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dashboardActionPerformed

    private void UsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsersMouseClicked
        // TODO add your handling code here:
        Point loc = this.getLocation();
        if (adWindow != null && adWindow.isVisible()) {
        adWindow.setVisible(false);
        adWindow.dispose();
        adWindow = null;
        }
        this.dispose();

        users ad = new users();
        ad.setLocation(loc);
        ad.setVisible(true);
    }//GEN-LAST:event_UsersMouseClicked

    private void UsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsersActionPerformed

    private void StatisticsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StatisticsMouseClicked
        // TODO add your handling code here:
        Point loc = this.getLocation();
        if (adWindow != null && adWindow.isVisible()) {
        adWindow.setVisible(false);
        adWindow.dispose();
        adWindow = null;
        }
        this.dispose();

        statistics ad = new statistics();
        ad.setLocation(loc);
        ad.setVisible(true);
    }//GEN-LAST:event_StatisticsMouseClicked

    private void StatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatisticsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatisticsActionPerformed

    private void ManageProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageProductsMouseClicked
        // TODO add your handling code here:
        Point loc = this.getLocation();
        if (adWindow != null && adWindow.isVisible()) {
        adWindow.setVisible(false);
        adWindow.dispose();
        adWindow = null;
        }
        this.dispose();

        manageproducts ad = new manageproducts();
        ad.setLocation(loc);
        ad.setVisible(true);
    }//GEN-LAST:event_ManageProductsMouseClicked

    private void ManageProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageProductsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManageProductsActionPerformed

    private void InvoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvoiceMouseClicked
        // TODO add your handling code here:
        Point loc = this.getLocation();
        if (adWindow != null && adWindow.isVisible()) {
        adWindow.setVisible(false);
        adWindow.dispose();
        adWindow = null;
        }
        this.dispose();

        invoice ad = new invoice();
        ad.setLocation(loc);
        ad.setVisible(true);
    }//GEN-LAST:event_InvoiceMouseClicked

    private void InvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InvoiceActionPerformed

    private void CalenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalenderMouseClicked
        // TODO add your handling code here:
        Point loc = this.getLocation();
        if (adWindow != null && adWindow.isVisible()) {
        adWindow.setVisible(false);
        adWindow.dispose();
        adWindow = null;
        }
        this.dispose();

        calender ad = new calender();
        ad.setLocation(loc);
        ad.setVisible(true);
    }//GEN-LAST:event_CalenderMouseClicked

    private void CalenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CalenderActionPerformed

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        Point loc = this.getLocation();
        if (adWindow != null && adWindow.isVisible()) {
        adWindow.setVisible(false);
        adWindow.dispose();
        adWindow = null;
        }
        this.dispose();

        Login loginPage = new Login();
        loginPage.setLocation(loc);
        loginPage.setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseEntered
        // TODO add your handling code here:
        dashboard.setBackground(new java.awt.Color(38,166,154)); 
        dashboard.setForeground(java.awt.Color.WHITE);
        dashboard.setBorder(
        BorderFactory.createLineBorder(new java.awt.Color(38,166,154), 2)
    );
        dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_dashboardMouseEntered

    private void dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseExited
        // TODO add your handling code here:
        dashboard.setBackground(new java.awt.Color(229,231,235)); 
        dashboard.setForeground(new java.awt.Color(107,114,128));
        dashboard.setBorder(
        BorderFactory.createLineBorder(new java.awt.Color(193,193,193), 2)
    );
    }//GEN-LAST:event_dashboardMouseExited

    private void UsersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsersMouseEntered
        // TODO add your handling code here:
        Users.setBackground(new java.awt.Color(38,166,154)); 
        Users.setForeground(java.awt.Color.WHITE);
        Users.setBorder(
        BorderFactory.createLineBorder(new java.awt.Color(38,166,154), 2)
    );
        Users.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_UsersMouseEntered

    private void UsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsersMouseExited
        // TODO add your handling code here:
        Users.setBackground(new java.awt.Color(229,231,235)); 
        Users.setForeground(new java.awt.Color(107,114,128));
        Users.setBorder(
        BorderFactory.createLineBorder(new java.awt.Color(193,193,193), 2)
    );
    }//GEN-LAST:event_UsersMouseExited

    private void StatisticsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StatisticsMouseEntered
        // TODO add your handling code here:
        Statistics.setBackground(new java.awt.Color(38,166,154)); 
        Statistics.setForeground(java.awt.Color.WHITE);
        Statistics.setBorder(
        BorderFactory.createLineBorder(new java.awt.Color(38,166,154), 2)
    );
        Statistics.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_StatisticsMouseEntered

    private void ManageProductsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageProductsMouseEntered
        // TODO add your handling code here:
        ManageProducts.setBackground(new java.awt.Color(38,166,154)); 
        ManageProducts.setForeground(java.awt.Color.WHITE);
        ManageProducts.setBorder(
        BorderFactory.createLineBorder(new java.awt.Color(38,166,154), 2)
    );
        Users.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_ManageProductsMouseEntered

    private void ManageProductsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageProductsMouseExited
        // TODO add your handling code here:
        ManageProducts.setBackground(new java.awt.Color(229,231,235)); 
        ManageProducts.setForeground(new java.awt.Color(107,114,128));
        ManageProducts.setBorder(
        BorderFactory.createLineBorder(new java.awt.Color(38,166,154), 2)
    );
    }//GEN-LAST:event_ManageProductsMouseExited

    private void InvoiceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvoiceMouseEntered
        // TODO add your handling code here:
        Invoice.setBackground(new java.awt.Color(38,166,154)); 
        Invoice.setForeground(java.awt.Color.WHITE);
        Invoice.setBorder(
        BorderFactory.createLineBorder(new java.awt.Color(38,166,154), 2)
    );
        Invoice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_InvoiceMouseEntered

    private void InvoiceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvoiceMouseExited
        // TODO add your handling code here:
        Invoice.setBackground(new java.awt.Color(229,231,235)); 
        Invoice.setForeground(new java.awt.Color(107,114,128));
        Invoice.setBorder(
        BorderFactory.createLineBorder(new java.awt.Color(193,193,193), 2)
    );
    }//GEN-LAST:event_InvoiceMouseExited

    private void CalenderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalenderMouseEntered
        // TODO add your handling code here:
        Calender.setBackground(new java.awt.Color(38,166,154)); 
        Calender.setForeground(java.awt.Color.WHITE);
        Calender.setBorder(
        BorderFactory.createLineBorder(new java.awt.Color(38,166,154), 2)
    );
        Calender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_CalenderMouseEntered

    private void CalenderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalenderMouseExited
        // TODO add your handling code here:
        Calender.setBackground(new java.awt.Color(229,231,235)); 
        Calender.setForeground(new java.awt.Color(107,114,128));
        Calender.setBorder(
        BorderFactory.createLineBorder(new java.awt.Color(193,193,193), 2)
    );
    }//GEN-LAST:event_CalenderMouseExited

    private void StatisticsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StatisticsMouseExited
        // TODO add your handling code here:
        Statistics.setBackground(new java.awt.Color(229,231,235)); 
        Statistics.setForeground(new java.awt.Color(107,114,128));
        Statistics.setBorder(
        BorderFactory.createLineBorder(new java.awt.Color(193,193,193), 2)
    );
    }//GEN-LAST:event_StatisticsMouseExited

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        // TODO add your handling code here:
        logout.setBackground(new java.awt.Color(38,166,154)); 
        logout.setForeground(java.awt.Color.WHITE);
        logout.setBorder(
        BorderFactory.createLineBorder(new java.awt.Color(38,166,154), 2)
    );
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        // TODO add your handling code here:
        logout.setBackground(new java.awt.Color(38,166,154)); 
        logout.setForeground(new java.awt.Color(255,255,255));
        logout.setBorder(
        BorderFactory.createLineBorder(new java.awt.Color(193,193,193), 2)
    );
    }//GEN-LAST:event_logoutMouseExited
    
    private int getSelectedProductId() {
    int row = ProductTable.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select a row first.");
        return -1;
    }
    return (int) ProductTable.getValueAt(row, 0); 
}
    
    private void restoreOldImageIfMissing(String oldImageName) {
    if (oldImageName == null || oldImageName.isBlank()) return;

    File f = new File("src/pictures", oldImageName);
    if (!f.exists()) {
        
        System.out.println("Old image " + oldImageName +
                           " is missing, cannot restore.");
    }
}

    
    private String chooseImageAndCopy() {
    JFileChooser chooser = new JFileChooser();
    chooser.setDialogTitle("Select product image");

    FileNameExtensionFilter filter =
        new FileNameExtensionFilter("Image files", "jpg", "jpeg", "png", "gif");
    chooser.setFileFilter(filter);

    int result = chooser.showOpenDialog(this);
    if (result != JFileChooser.APPROVE_OPTION) {
        return null; 
    }

    File selectedFile = chooser.getSelectedFile();
    String imageName = selectedFile.getName();      

    
    File destDir = new File("src/pictures");
    if (!destDir.exists() && !destDir.mkdirs()) {
        JOptionPane.showMessageDialog(this,
                "Cannot create src/pictures folder.");
        return null;
    }

    File destFile = new File(destDir, imageName);

    try {
        Files.copy(selectedFile.toPath(), destFile.toPath(),
                   StandardCopyOption.REPLACE_EXISTING);
    } catch (IOException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this,
            "Could not copy image: " + ex.getMessage());
        return null;
    }

    return imageName;  
}
    
    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
        // TODO add your handling code here:
        int productId = getSelectedProductId();
    if (productId == -1) return;

    ProductController controller = new ProductController();
    ProductModel product = controller.getProductById(productId);
    if (product == null) {
        JOptionPane.showMessageDialog(this, "Product not found.");
        return;
    }

    String newName = JOptionPane.showInputDialog(
            this, "Name:", product.getProductName());
    String oldImageName = product.getProductImage();

    
    String newImage = chooseImageAndCopy();       
    if (newImage == null) {
        
        newImage = oldImageName;
    }

    String newPriceStr = JOptionPane.showInputDialog(
            this, "Price:", product.getProductPrice());
    String newSynopsis = JOptionPane.showInputDialog(
            this, "Synopsis:", product.getProductSynopsis());
    String newType = JOptionPane.showInputDialog(
            this, "Type:", product.getProductType());
    String newForm = JOptionPane.showInputDialog(
            this, "Form:", product.getProductForm());
    String newQtyStr = JOptionPane.showInputDialog(
            this, "QTY:", product.getProductQuantity());

    
    
    if (newName == null || newImage == null || newPriceStr == null ||
        newSynopsis == null || newType == null || newForm == null ||
        newQtyStr == null) {

        if (newImage != null && !newImage.equals(oldImageName)) {
            File f = new File("src/pictures", newImage);
            if (f.exists()) f.delete();
        }
        return;
    }

    int newPrice = Integer.parseInt(newPriceStr);
    int newQty = Integer.parseInt(newQtyStr);

    product.setProductName(newName);
    product.setProductImage(newImage);
    product.setProductPrice(newPrice);
    product.setProductSynopsis(newSynopsis);
    product.setProductType(newType);
    product.setProductForm(newForm);
    product.setProductQuantity(newQty);

    try {
        controller.updateProduct(product);    

       
        if (oldImageName != null && !oldImageName.isBlank()
                && !oldImageName.equals(newImage)) {
            File oldFile = new File("src/pictures", oldImageName);
            if (oldFile.exists()) {
                boolean deleted = oldFile.delete();
                System.out.println("Old image deleted: " + deleted);
            }
        }
    } catch (Exception ex) {
        
        if (newImage != null && !newImage.equals(oldImageName)) {
            File newFile = new File("src/pictures", newImage);
            if (newFile.exists()) newFile.delete();
        }
        JOptionPane.showMessageDialog(this,
                "Error updating product: " + ex.getMessage());
        restoreOldImageIfMissing(oldImageName);
        return;
    }

    loadProductsToTable();
    }//GEN-LAST:event_editMouseClicked

    private void editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseEntered
        // TODO add your handling code here:
        edit.setBackground(new java.awt.Color(2, 62, 138));
        edit.setForeground(java.awt.Color.WHITE);
        edit.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(2, 62, 138), 2)
        );
        edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_editMouseEntered

    private void editMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseExited
        // TODO add your handling code here:
        edit.setBackground(normalBg);
        edit.setForeground(normalFg);
        edit.setBorder(normalBorder);
        edit.setCursor(normalCursor);
    }//GEN-LAST:event_editMouseExited
    
    private String getSelectedProductImageName() {
    int row = ProductTable.getSelectedRow();
    if (row == -1) return null;
    Object val = ProductTable.getValueAt(row, 2); 
    return val == null ? null : val.toString();
}
    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        // TODO add your handling code here:
        int productId = getSelectedProductId();
    if (productId == -1) return;

    String imageName = getSelectedProductImageName();

    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Delete this product?",
            "Confirm delete",
            JOptionPane.YES_NO_OPTION);

    if (confirm != JOptionPane.YES_OPTION) return;

    
    try {
        productController.deleteProduct(productId);  
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error deleting product: " + ex.getMessage());
        return;
    }

    
    if (imageName != null && !imageName.isBlank()) {
        File img = new File("src/pictures", imageName);
        if (img.exists()) {
            boolean deleted = img.delete();
            System.out.println("Deleted image " + imageName + ": " + deleted);
        }
    }

    
    loadProductsToTable();
    }//GEN-LAST:event_deleteMouseClicked

    private void deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseEntered
        // TODO add your handling code here:
        delete.setBackground(new java.awt.Color(193, 18, 31));
        delete.setForeground(java.awt.Color.WHITE);
        delete.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(193, 18, 31), 2)
        );
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_deleteMouseEntered

    private void deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseExited
        // TODO add your handling code here:
        delete.setBackground(defaultBg);
        delete.setForeground(defaultFg);
        delete.setBorder(defaultBorder);
        delete.setCursor(defaultCursor);
    }//GEN-LAST:event_deleteMouseExited
    
    private void deleteImageIfExists(String imageName) {
    if (imageName == null || imageName.isBlank()) return;
    File f = new File("src/pictures", imageName);
    if (f.exists()) {
        boolean deleted = f.delete();
        System.out.println("Rollback image delete " + imageName + ": " + deleted);
    }
}

    private void addproductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addproductMouseClicked
        // TODO add your handling code here:                                       
     String imageName = null;

    try {
        
        String name = JOptionPane.showInputDialog(this, "Name:");
        if (name == null || name.isBlank()) return;   

       
        imageName = chooseImageAndCopy();             
        if (imageName == null) return;                

        
        String priceStr = JOptionPane.showInputDialog(this, "Price:");
        if (priceStr == null || priceStr.isBlank()) {
            deleteImageIfExists(imageName);
            return;
        }

     
        String synopsis = JOptionPane.showInputDialog(this, "Synopsis:");
        if (synopsis == null) synopsis = "";

        
        String type = JOptionPane.showInputDialog(this, "Type (Book/Movie):");
        if (type == null) {
            deleteImageIfExists(imageName);
            return;
        }

        
        String form = JOptionPane.showInputDialog(this, "Form (Physical/Digital):");
        if (form == null) {
            deleteImageIfExists(imageName);
            return;
        }

        
        String qtyStr = JOptionPane.showInputDialog(this, "QTY:");
        if (qtyStr == null || qtyStr.isBlank()) {
            deleteImageIfExists(imageName);
            return;
        }

        int price = Integer.parseInt(priceStr);
        int qty   = Integer.parseInt(qtyStr);

        ProductModel product = new ProductModel(
            name, imageName, price, synopsis, type, form, qty
        );

        
        productController.addProduct(product);    
        loadProductsToTable();
        JOptionPane.showMessageDialog(this, "Product added.");

        
        imageName = null;
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error adding product: " + ex.getMessage());
    } finally {
        
        if (imageName != null) {
            deleteImageIfExists(imageName);
        }
    }
    }//GEN-LAST:event_addproductMouseClicked

    private void addproductMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addproductMouseEntered
        // TODO add your handling code here:
        addproduct.setBackground(new java.awt.Color(255, 255, 255));
        addproduct.setForeground(new java.awt.Color(2, 62, 138));
        addproduct.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(2, 62, 138), 2)
        );
        addproduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_addproductMouseEntered

    private void addproductMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addproductMouseExited
        // TODO add your handling code here:
        addproduct.setBackground(originalBg);
        addproduct.setForeground(originalFg);
        addproduct.setBorder(originalBorder);
        addproduct.setCursor(originalCursor);
    }//GEN-LAST:event_addproductMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new manageproducts().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calender;
    private javax.swing.JButton Invoice;
    private javax.swing.JButton ManageProducts;
    private javax.swing.JTable ProductTable;
    private javax.swing.JLabel ProfileIcon;
    private javax.swing.JButton Statistics;
    private javax.swing.JButton Users;
    private javax.swing.JButton addproduct;
    private javax.swing.JPanel background;
    private javax.swing.JPanel center;
    private javax.swing.JButton dashboard;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logout;
    private javax.swing.JPanel mainlogo;
    private javax.swing.JPanel notification;
    private javax.swing.JButton notificationicon;
    private javax.swing.JPanel profile;
    private javax.swing.JLabel rentifylogo;
    // End of variables declaration//GEN-END:variables
}
