/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author sthaa
 */
public class notification extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(notification.class.getName());
    /**
     * Creates new form notification
     */
    public notification() {
        this.setUndecorated(true); 
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        notificationpanel = new javax.swing.JPanel();
        clean = new javax.swing.JButton();
        notificationmessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        notificationpanel.setBackground(new java.awt.Color(249, 250, 251));
        notificationpanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.LineBorder(new java.awt.Color(38, 166, 154), 1, true)));
        notificationpanel.setPreferredSize(new java.awt.Dimension(300, 400));
        notificationpanel.setLayout(null);

        clean.setBackground(new java.awt.Color(238, 238, 238));
        clean.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clean.setText("Clean");
        clean.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 10, 4, 10));
        clean.setBorderPainted(false);
        clean.setFocusPainted(false);
        clean.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cleanMouseClicked(evt);
            }
        });
        clean.addActionListener(this::cleanActionPerformed);
        notificationpanel.add(clean);
        clean.setBounds(224, 358, 60, 30);

        notificationmessage.setBackground(new java.awt.Color(249, 250, 251));
        notificationmessage.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        notificationmessage.setForeground(new java.awt.Color(38, 166, 154));
        notificationmessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        notificationpanel.add(notificationmessage);
        notificationmessage.setBounds(10, 30, 280, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(notificationpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(notificationpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cleanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cleanMouseClicked
        // TODO add your handling code here:
        if (notificationmessage != null) {
        notificationmessage.setText("");
    }
    }//GEN-LAST:event_cleanMouseClicked

    private void cleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cleanActionPerformed
    public void setMessage(String msg) {
    notificationmessage.setText(msg);
}
    public void clearMessage() {
    notificationmessage.setText("");
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new notification().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clean;
    private javax.swing.JLabel notificationmessage;
    private javax.swing.JPanel notificationpanel;
    // End of variables declaration//GEN-END:variables
}
