/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import userdata.ProductDao;
import model.ProductModel;

/**
 *
 * @author zenni
 */
public class ProductPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProductPage.class.getName());


    /**
     * Creates new form productPage
     */
    
    private ProductDao productDao = new ProductDao();
    
    public ProductPage(int productId) {
        initComponents();
        loadProduct(productId);
    }
    
        private void loadProduct(int productId) {
    ProductModel p = productDao.getProductById(productId);
    if (p == null) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Product not found: " + productId);
        return;
    }

    itemName.setText(p.getProductName());
    directorName.setText(p.getProductSynopsis());  // or another field
    jLabel9.setText("Rs. " + p.getProductPrice());

    try {
        javax.swing.ImageIcon icon =
                new javax.swing.ImageIcon(getClass().getResource(p.getProductImage()));
        Profile_icon6.setIcon(icon);
    } catch (Exception e) {
        e.printStackTrace();
    }
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Profile_icon6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        itemName = new javax.swing.JLabel();
        directorName = new javax.swing.JLabel();
        Synopsis = new javax.swing.JTextArea();
        rateBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();
        Support = new javax.swing.JButton();
        Library = new javax.swing.JButton();
        Movies = new javax.swing.JButton();
        Newest = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Books = new javax.swing.JButton();
        cart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 231, 235), 3));

        jPanel3.setBackground(new java.awt.Color(229, 231, 235));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 231, 235)));
        jPanel3.setPreferredSize(new java.awt.Dimension(3, 560));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
        );

        Profile_icon6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Johnwickposter.jpg"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("Rs. 899");

        itemName.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        itemName.setForeground(new java.awt.Color(0, 0, 0));
        itemName.setText("John Wick");

        directorName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        directorName.setForeground(new java.awt.Color(0, 0, 0));
        directorName.setText("Chad Stahelski");

        Synopsis.setBackground(new java.awt.Color(255, 255, 255));
        Synopsis.setColumns(20);
        Synopsis.setForeground(new java.awt.Color(0, 0, 0));
        Synopsis.setText("After the death of his wife, retired hitman John Wick mourns in solitude, finding solace in memories and the companionship of a dog \nshe left behind. When a violent act by local criminals destroys this final connection, John is pulled back into the criminal underworld he \nhad left behind. As he confronts former allies and enemies, his unmatched skills and tactical precision are revealed, and he systematically\ndismantles those responsible. The story explores themes of loss, revenge, and the strict codes governing the shadowy world of assassins, \nshowcasing John's relentless determination and the consequences of crossing him.");

        rateBtn.setBackground(new java.awt.Color(255, 255, 255));
        rateBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rateBtn.setForeground(new java.awt.Color(0, 0, 0));
        rateBtn.setText("Rate this movie?");
        rateBtn.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(Profile_icon6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(directorName)
                            .addComponent(itemName)
                            .addComponent(Synopsis, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(jLabel9))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(rateBtn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(245, 245, 245))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Profile_icon6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(itemName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(directorName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Synopsis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(rateBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(25, 140, 1230, 565);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/rentifyohnebg (1).png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 260, 60);

        jTextArea1.setBackground(new java.awt.Color(229, 231, 235));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(jTextArea1);
        jTextArea1.setBounds(820, 100, 230, 30);

        Support.setBackground(new java.awt.Color(232, 241, 253));
        Support.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        Support.setForeground(new java.awt.Color(17, 24, 39));
        Support.setText("Support");
        Support.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupportActionPerformed(evt);
            }
        });
        jPanel1.add(Support);
        Support.setBounds(990, 50, 146, 36);

        Library.setBackground(new java.awt.Color(232, 241, 253));
        Library.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        Library.setForeground(new java.awt.Color(17, 24, 39));
        Library.setText("Library");
        Library.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibraryActionPerformed(evt);
            }
        });
        jPanel1.add(Library);
        Library.setBounds(310, 50, 146, 36);

        Movies.setBackground(new java.awt.Color(232, 241, 253));
        Movies.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        Movies.setForeground(new java.awt.Color(17, 24, 39));
        Movies.setText("Movies");
        Movies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoviesActionPerformed(evt);
            }
        });
        jPanel1.add(Movies);
        Movies.setBounds(650, 50, 146, 36);

        Newest.setBackground(new java.awt.Color(232, 241, 253));
        Newest.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        Newest.setForeground(new java.awt.Color(17, 24, 39));
        Newest.setText("Newest");
        Newest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewestActionPerformed(evt);
            }
        });
        jPanel1.add(Newest);
        Newest.setBounds(820, 50, 146, 36);

        jButton1.setBackground(new java.awt.Color(229, 231, 235));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search-icon.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1050, 100, 40, 30);

        Books.setBackground(new java.awt.Color(232, 241, 253));
        Books.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        Books.setForeground(new java.awt.Color(17, 24, 39));
        Books.setText("Books");
        Books.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BooksActionPerformed(evt);
            }
        });
        jPanel1.add(Books);
        Books.setBounds(480, 50, 146, 36);

        cart.setBackground(new java.awt.Color(255, 255, 255));
        cart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cart40x40.png"))); // NOI18N
        cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartActionPerformed(evt);
            }
        });
        jPanel1.add(cart);
        cart.setBounds(1100, 100, 40, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SupportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SupportActionPerformed

    private void LibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibraryActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_LibraryActionPerformed

    private void MoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoviesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MoviesActionPerformed

    private void NewestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewestActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BooksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BooksActionPerformed

    private void cartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
   java.awt.EventQueue.invokeLater(() -> new ProductPage(1).setVisible(true));    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Books;
    private javax.swing.JButton Library;
    private javax.swing.JButton Movies;
    private javax.swing.JButton Newest;
    private javax.swing.JLabel Profile_icon6;
    private javax.swing.JButton Support;
    private javax.swing.JTextArea Synopsis;
    private javax.swing.JButton cart;
    private javax.swing.JLabel directorName;
    private javax.swing.JLabel itemName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton rateBtn;
    // End of variables declaration//GEN-END:variables
}
