/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.userController;
import javax.swing.JOptionPane;
import model.User_model;
     
 
/**
 *
 * @author ASUS
 */
public class registration extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(registration.class.getName());

    /**
     * Creates new form registration
     */
    public registration() {
        initComponents();
        
        userController controller = new userController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(249, 250, 251));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Registration");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 100, 130, 32);

        jTextField1.setBackground(new java.awt.Color(247, 249, 255));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(150, 150, 150));
        jTextField1.setText("Full Name");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(60, 160, 319, 39);

        jTextField2.setBackground(new java.awt.Color(247, 249, 255));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(150, 150, 150));
        jTextField2.setText("Username");
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(60, 220, 319, 39);

        jTextField3.setEditable(true);
        jTextField3.setBackground(new java.awt.Color(247, 249, 255));
        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(150, 150, 150));
        jTextField3.setText("Email");
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(60, 280, 319, 39);

        jPasswordField1.setBackground(new java.awt.Color(247, 249, 255));
        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(60, 340, 319, 39);

        jButton1.setBackground(new java.awt.Color(13, 106, 210));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(80, 420, 250, 45);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/rentify-200.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 10, 210, 80);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(425, 100, 430, 567);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String fullname = jTextField1.getText().trim();
        String username = jTextField2.getText().trim();
        String email    = jTextField3.getText().trim();
        String password = new String(jPasswordField1.getPassword()).trim();     

     if (fullname.isEmpty() || fullname.equals("Full Name")) {
        JOptionPane.showMessageDialog(this,
                "Please enter your full name.",
                "Validation error",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (username.isEmpty() || username.equals("Username")) {
        JOptionPane.showMessageDialog(this,
                "Please enter a username.",
                "Validation error",
                JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    if (email.isEmpty() || email.equals("Email")) {
        JOptionPane.showMessageDialog(this,
                "Please enter your email.",
                "Validation error",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (password.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Please enter a password.",
                "Validation error",
                JOptionPane.ERROR_MESSAGE);
        return;
    }
    
     String emailRegex = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$";
    if (!email.matches(emailRegex)) {
        JOptionPane.showMessageDialog(this,
                "Please enter a valid email address (e.g. user@example.com).",
                "Invalid email",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 3. Password rule (example: at least 6 characters)
    if (password.length() < 6) {
        JOptionPane.showMessageDialog(this,
                "Password must be at least 6 characters long.",
                "Invalid password",
                JOptionPane.ERROR_MESSAGE);
        return;
    }
    
  

    // 4. Now create the model and hit DAO only if validation passed
    User_model user = new User_model(username, email, password);
    userdata.userDao dao = new userdata.userDao();
    
        user.setUsername(username);
        user.setEmail(email);
        user.setPasssword(password); 


    // 5. Check if email/username already exists
    if (dao.check(user)) {
        JOptionPane.showMessageDialog(this,
                "Email or username already exists.",
                "Registration error",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 6. Save user
    dao.signup(user, fullname);
    JOptionPane.showMessageDialog(this,
            "Registration successful!",
            "Success",
            JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
      if (jTextField1.getText().equals("Full Name")) {
        jTextField1.setText("");
}       // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
      if (jTextField1.getText().isEmpty()) {
        jTextField1.setText("Full Name");
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
      if (jTextField2.getText().equals("Username")) {
        jTextField2.setText("");
}    // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2FocusGained

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
      if (jTextField2.getText().isEmpty()) {
        jTextField2.setText("Username");
    }      // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2FocusLost

    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusGained
      if (jTextField3.getText().equals("Email")) {
        jTextField3.setText("");
    }     // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3FocusGained

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
      if (jTextField3.getText().isEmpty()) {
        jTextField3.setText("Email");
    }     // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3FocusLost

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
          jPasswordField1.setText("");
         jPasswordField1.setEchoChar('*');
    
      
      // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusLost
       if(String.valueOf(jPasswordField1.getPassword()).isEmpty()){
          
         }
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1FocusLost

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new registration().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTextField getFullNameField(){
        return jTextField1;
    }
    
    public javax.swing.JTextField getUsernameField(){
        return jTextField2;
    }
    
    public javax.swing.JTextField getEmailField(){
        return jTextField3;
    }
    
    public javax.swing.JPasswordField getPasswordField(){
        return jPasswordField1;
    }
    
    public void addUserListener(java.awt.event.ActionListener l){
        jButton1.addActionListener(l);
    }

}
