/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;
import view.wishlist;

/**
 *
 * @author zenni
 */
public class UserDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserDashboard.class.getName());

    /**
     * Creates new form dashboard
     */
    private int currentUserId;
    
    public UserDashboard() {
        initComponents();
        setSize(1293,760);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ProfileBTN = new javax.swing.JButton();
        OrdersBTN = new javax.swing.JButton();
        HistoryBTN = new javax.swing.JButton();
        WishlistBTN = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        userEmail = new javax.swing.JLabel();
        Profile_icon1 = new javax.swing.JLabel();
        userFullName = new javax.swing.JLabel();
        LogoutBTN = new javax.swing.JButton();
        Profile_icon3 = new javax.swing.JLabel();
        Profile_icon4 = new javax.swing.JLabel();
        Profile_icon5 = new javax.swing.JLabel();
        Profile_icon6 = new javax.swing.JLabel();
        Profile_icon7 = new javax.swing.JLabel();
        Profile_icon8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Profile_icon9 = new javax.swing.JLabel();
        SupportBTN = new javax.swing.JButton();
        LibraryBTN = new javax.swing.JButton();
        MoviesBTN = new javax.swing.JButton();
        NewestBTN = new javax.swing.JButton();
        BooksBTN = new javax.swing.JButton();
        SearchBOX = new javax.swing.JTextArea();
        SearchBTN = new javax.swing.JButton();
        cart = new javax.swing.JButton();
        profileIconBTN = new javax.swing.JButton();
        LogoBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 231, 235), 3));

        ProfileBTN.setBackground(new java.awt.Color(255, 255, 255));
        ProfileBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        ProfileBTN.setForeground(new java.awt.Color(107, 114, 128));
        ProfileBTN.setText("Profile");
        ProfileBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 166, 154)));
        ProfileBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileBTNActionPerformed(evt);
            }
        });

        OrdersBTN.setBackground(new java.awt.Color(255, 255, 255));
        OrdersBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        OrdersBTN.setForeground(new java.awt.Color(107, 114, 128));
        OrdersBTN.setText("Orders");
        OrdersBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 166, 154)));
        OrdersBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdersBTNActionPerformed(evt);
            }
        });

        HistoryBTN.setBackground(new java.awt.Color(255, 255, 255));
        HistoryBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        HistoryBTN.setForeground(new java.awt.Color(107, 114, 128));
        HistoryBTN.setText("History");
        HistoryBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 166, 154)));
        HistoryBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryBTNActionPerformed(evt);
            }
        });

        WishlistBTN.setBackground(new java.awt.Color(255, 255, 255));
        WishlistBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        WishlistBTN.setForeground(new java.awt.Color(107, 114, 128));
        WishlistBTN.setText("Wishlist");
        WishlistBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 166, 154)));
        WishlistBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WishlistBTNActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(229, 231, 235));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 231, 235)));
        jPanel3.setPreferredSize(new java.awt.Dimension(3, 560));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
        );

        userEmail.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        userEmail.setForeground(new java.awt.Color(51, 51, 51));
        userEmail.setText("ashishshrestha250@gmail.com");

        Profile_icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/harrypotterHBPcover.jpg"))); // NOI18N

        userFullName.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        userFullName.setForeground(new java.awt.Color(51, 51, 51));
        userFullName.setText("Ashish Shrestha");

        LogoutBTN.setBackground(new java.awt.Color(38, 166, 154));
        LogoutBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        LogoutBTN.setForeground(new java.awt.Color(255, 255, 255));
        LogoutBTN.setText("Logout");
        LogoutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBTNActionPerformed(evt);
            }
        });

        Profile_icon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/profile-85x85.png"))); // NOI18N

        Profile_icon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/harrypotterTPScover.jpg"))); // NOI18N

        Profile_icon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Transformersposter.jpg"))); // NOI18N

        Profile_icon6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Johnwickposter.jpg"))); // NOI18N

        Profile_icon7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Profile_icon7.setForeground(new java.awt.Color(51, 51, 51));
        Profile_icon7.setText("Transformers");

        Profile_icon8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Profile_icon8.setForeground(new java.awt.Color(51, 51, 51));
        Profile_icon8.setText("Harry Potter and");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("The Half-blood Prince ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Philosophers' stone");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Harry Potter and the");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("John wick");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("Rs. 1100");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setText("Rs. 999");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setText("Rs. 1299");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("Rs. 899");

        Profile_icon9.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        Profile_icon9.setForeground(new java.awt.Color(51, 51, 51));
        Profile_icon9.setText("Favourites");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(WishlistBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HistoryBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrdersBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProfileBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogoutBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(Profile_icon3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userFullName)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(userEmail)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(Profile_icon5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(Profile_icon7))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jLabel7)))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Profile_icon1)
                            .addComponent(Profile_icon8, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addContainerGap())
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Profile_icon4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(Profile_icon6)
                                        .addGap(37, 37, 37))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel5))
                                        .addGap(73, 73, 73))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(Profile_icon9)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(ProfileBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(OrdersBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(HistoryBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(WishlistBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(userFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(userEmail))
                            .addComponent(Profile_icon3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Profile_icon9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Profile_icon4)
                            .addComponent(Profile_icon1)
                            .addComponent(Profile_icon6)
                            .addComponent(Profile_icon5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Profile_icon7)
                            .addComponent(Profile_icon8)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(LogoutBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(25, 140, 1230, 565);

        SupportBTN.setBackground(new java.awt.Color(232, 241, 253));
        SupportBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        SupportBTN.setForeground(new java.awt.Color(17, 24, 39));
        SupportBTN.setText("Support");
        SupportBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupportBTNActionPerformed(evt);
            }
        });
        jPanel1.add(SupportBTN);
        SupportBTN.setBounds(990, 50, 146, 36);

        LibraryBTN.setBackground(new java.awt.Color(232, 241, 253));
        LibraryBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        LibraryBTN.setForeground(new java.awt.Color(17, 24, 39));
        LibraryBTN.setText("Library");
        LibraryBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibraryBTNActionPerformed(evt);
            }
        });
        jPanel1.add(LibraryBTN);
        LibraryBTN.setBounds(310, 50, 146, 36);

        MoviesBTN.setBackground(new java.awt.Color(232, 241, 253));
        MoviesBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        MoviesBTN.setForeground(new java.awt.Color(17, 24, 39));
        MoviesBTN.setText("Movies");
        MoviesBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoviesBTNActionPerformed(evt);
            }
        });
        jPanel1.add(MoviesBTN);
        MoviesBTN.setBounds(650, 50, 146, 36);

        NewestBTN.setBackground(new java.awt.Color(232, 241, 253));
        NewestBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        NewestBTN.setForeground(new java.awt.Color(17, 24, 39));
        NewestBTN.setText("Newest");
        NewestBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewestBTNActionPerformed(evt);
            }
        });
        jPanel1.add(NewestBTN);
        NewestBTN.setBounds(820, 50, 146, 36);

        BooksBTN.setBackground(new java.awt.Color(232, 241, 253));
        BooksBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        BooksBTN.setForeground(new java.awt.Color(17, 24, 39));
        BooksBTN.setText("Books");
        BooksBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BooksBTNActionPerformed(evt);
            }
        });
        jPanel1.add(BooksBTN);
        BooksBTN.setBounds(480, 50, 146, 36);

        SearchBOX.setBackground(new java.awt.Color(229, 231, 235));
        SearchBOX.setColumns(20);
        SearchBOX.setRows(5);
        SearchBOX.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(SearchBOX);
        SearchBOX.setBounds(820, 100, 230, 30);

        SearchBTN.setBackground(new java.awt.Color(229, 231, 235));
        SearchBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search-icon.png"))); // NOI18N
        SearchBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        SearchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBTNActionPerformed(evt);
            }
        });
        jPanel1.add(SearchBTN);
        SearchBTN.setBounds(1050, 100, 40, 30);

        cart.setBackground(new java.awt.Color(255, 255, 255));
        cart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cart40x40.png"))); // NOI18N
        cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartActionPerformed(evt);
            }
        });
        jPanel1.add(cart);
        cart.setBounds(1100, 100, 40, 40);

        profileIconBTN.setBackground(new java.awt.Color(255, 255, 255));
        profileIconBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        profileIconBTN.setForeground(new java.awt.Color(17, 24, 39));
        profileIconBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/profile-85x85.png"))); // NOI18N
        profileIconBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileIconBTNActionPerformed(evt);
            }
        });
        jPanel1.add(profileIconBTN);
        profileIconBTN.setBounds(1180, 10, 90, 90);

        LogoBTN.setBackground(new java.awt.Color(255, 255, 255));
        LogoBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/rentifyohnebg (1).png"))); // NOI18N
        LogoBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        LogoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoBTNActionPerformed(evt);
            }
        });
        jPanel1.add(LogoBTN);
        LogoBTN.setBounds(10, 10, 260, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProfileBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProfileBTNActionPerformed

    private void OrdersBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdersBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrdersBTNActionPerformed

    private void HistoryBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HistoryBTNActionPerformed

    private void WishlistBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WishlistBTNActionPerformed
        // TODO add your handling code here:
        wishlist WishlistPage = new wishlist(currentUserId);
        WishlistPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_WishlistBTNActionPerformed

    private void SupportBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupportBTNActionPerformed
        // TODO add your handling code here:
        
        ProductPage productPage = new ProductPage(1);
        productPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SupportBTNActionPerformed

    private void LibraryBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibraryBTNActionPerformed
        // TODO add your handling code here:
        LibraryPage libraryPage = new LibraryPage();
        libraryPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LibraryBTNActionPerformed

    private void LogoutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBTNActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_LogoutBTNActionPerformed

    private void MoviesBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoviesBTNActionPerformed
        // TODO add your handling code here:
    // Navigate to Profile Page
        MoviePage moviePage = new MoviePage();
        moviePage.setVisible(true);
        this.dispose(); // Close current dashboard

    }//GEN-LAST:event_MoviesBTNActionPerformed

    private void NewestBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewestBTNActionPerformed
        // TODO add your handling code here:
        NewestPage newestPage = new NewestPage();
        newestPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_NewestBTNActionPerformed

    private void BooksBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BooksBTNActionPerformed
        // TODO add your handling code here:
        BooksPage booksPage = new BooksPage();
        booksPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BooksBTNActionPerformed

    private void SearchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBTNActionPerformed
        // TODO add your handling code here:
        ProductPage productPage = new ProductPage(1);
        productPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SearchBTNActionPerformed

    private void cartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cartActionPerformed

    private void profileIconBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileIconBTNActionPerformed
        // TODO add your handling code here:
        UserDashboard userDashboard = new UserDashboard();
        userDashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_profileIconBTNActionPerformed

    private void LogoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoBTNActionPerformed
        // TODO add your handling code here:
        HomePage homePage = new HomePage();
        homePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BooksBTN;
    private javax.swing.JButton HistoryBTN;
    private javax.swing.JButton LibraryBTN;
    private javax.swing.JButton LogoBTN;
    private javax.swing.JButton LogoutBTN;
    private javax.swing.JButton MoviesBTN;
    private javax.swing.JButton NewestBTN;
    private javax.swing.JButton OrdersBTN;
    private javax.swing.JButton ProfileBTN;
    private javax.swing.JLabel Profile_icon1;
    private javax.swing.JLabel Profile_icon3;
    private javax.swing.JLabel Profile_icon4;
    private javax.swing.JLabel Profile_icon5;
    private javax.swing.JLabel Profile_icon6;
    private javax.swing.JLabel Profile_icon7;
    private javax.swing.JLabel Profile_icon8;
    private javax.swing.JLabel Profile_icon9;
    private javax.swing.JTextArea SearchBOX;
    private javax.swing.JButton SearchBTN;
    private javax.swing.JButton SupportBTN;
    private javax.swing.JButton WishlistBTN;
    private javax.swing.JButton cart;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton profileIconBTN;
    private javax.swing.JLabel userEmail;
    private javax.swing.JLabel userFullName;
    // End of variables declaration//GEN-END:variables
    
  
}
